// Generated by CoffeeScript 1.6.3
(function() {
  var initAnimation;

  initAnimation = function() {
    var animate, g, nextFrame, particleBuffer, particles, startTime;
    g = globe.create();
    g.init({
      container: document.body,
      globeTexture: '../../natural-earth.jpg',
      atmosphere: false
    });
    particles = g.createParticles({
      particleCount: 5000,
      size: 5,
      opacity: 0
    });
    particles.add();
    particleBuffer = new globe.ParticleBuffer(particles);
    nextFrame = function(t) {
      var point;
      point = {
        lng: Math.random() * 360 - 180,
        lat: Math.random() * 180 - 90
      };
      particleBuffer.allocate([point], function(point, particle) {
        particle.reset();
        particle.setOpacity(1);
        particle.setPosition(point.lng, point.lat);
        particle.startT = t;
        particle.endT = t + 1000;
        return particle.removeT = t + 1000;
      });
      return particleBuffer.update(t, function(particle) {
        var pos;
        pos = (t - particle.startT) / (particle.removeT - particle.startT);
        particle.setAltitude(pos);
        if (pos > 0.9) {
          return particle.setOpacity((1 - pos) / 0.1);
        }
      });
    };
    startTime = Date.now();
    animate = function() {
      return window.requestAnimationFrame(function(t) {
        nextFrame(t - startTime);
        return animate();
      });
    };
    animate();
    globe.observeMouse(g.satellite, g.domElement);
    return g.initAnimation();
  };

  $(initAnimation);

}).call(this);
